//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCatalog
    {
        public MenuCatalog()
        {
            this.MenuCatalogLocalizations = new HashSet<MenuCatalogLocalization>();
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public System.Guid ID { get; set; }
        public string ParentID { get; set; }
        public System.Guid OrganizationID { get; set; }
        public string CatalogLevelName { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<MenuCatalogLocalization> MenuCatalogLocalizations { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
