//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItemLocalizations = new HashSet<MenuItemLocalization>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid MenuCatalog_ID { get; set; }
        public int MenuItemPrice { get; set; }
        public bool IsActive { get; set; }
    
        public virtual MenuCatalog MenuCatalog { get; set; }
        public virtual ICollection<MenuItemLocalization> MenuItemLocalizations { get; set; }
    }
}
