//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.MenuCatalogs = new HashSet<MenuCatalog>();
            this.OrganizationPhoneNumbers = new HashSet<OrganizationPhoneNumber>();
            this.TableReservations = new HashSet<TableReservation>();
        }
    
        public System.Guid ID { get; set; }
        public string OrganizationName { get; set; }
        public System.Guid OrganizationTypeID { get; set; }
        public string OrganizationAddress { get; set; }
        public bool IsActive { get; set; }
        public byte[] OrganizationLogo { get; set; }
    
        public virtual ICollection<MenuCatalog> MenuCatalogs { get; set; }
        public virtual OrganizationType OrganizationType { get; set; }
        public virtual ICollection<OrganizationPhoneNumber> OrganizationPhoneNumbers { get; set; }
        public virtual ICollection<TableReservation> TableReservations { get; set; }
    }
}
